// <auto-generated />
namespace ATP2B1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Customer_Override : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Customer_Override));
        
        string IMigrationMetadata.Id
        {
            get { return "201802160835440_Customer_Override"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
